### PR TITLE
Adding a DocParser for Docstrings in scripts

### PR DESCRIPTION
**Pull request by davudevren**
Template for Doc:
##
##
## @ENV_NAME2 Andere Enviroment variable

### CODE REVIEW

**Comment by TheChymera** [comment]
@davudevren thanks for the PR, great work! As you can see, however, it's trying to merge a lot of stuff which you didn't do. This is because you created your branch after @Doeme submitted a few commits which were broken commits, and which he has in the mean time overwritten with corrected versions.

The smart version to solve this problem involves git commit picking and rebasing. If you are interested in the more advanced features of git, this is certainly the way to go.

If you do not want to learn more about this tool, you can just copy the files you know you edited into a location outside of the repo, delete your copy of the repo (in case you have no other unfinished original work not integrated into the main repo), create a fresh copy (cloned with the current history), and copy your files on top.

**Comment by Doeme** [comment]
Got inpatient and merged it using a `git cherry-pick`, see https://github.com/IBT-FMI/gebuilder/commit/e7ff3e1f348e13c010152a8ccfe11afee050be8c

Thank you for helping us help you help us all!
asdf

**Comment by davudevren** [comment]
Thank you @Doeme and @TheChymera .
Sorry for being late. I thought i merged the master to my branch and pushed it, but i think i did something wrong (much to practice with git) `git cherry-pick` locks nice !

**Comment by Doeme** [comment]
> I thought i merged the master to my branch and pushed it, but i think i did something wrong (much to practice with git) git cherry-pick locks nice !

You did everything right. It was I who fucked it up, by force pushing on the master branch (something you should not do)

**Pull request closed without merging**
